--- libs/link/AbletonLinkConfig.cmake.orig	2021-12-03 12:55:21 UTC
+++ libs/link/AbletonLinkConfig.cmake
@@ -31,7 +31,8 @@ elseif(WIN32)
     INTERFACE_COMPILE_DEFINITIONS
     LINK_PLATFORM_WINDOWS=1
   )
-elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux" OR ${CMAKE_SYSTEM_NAME} MATCHES "kFreeBSD" OR ${CMAKE_SYSTEM_NAME} MATCHES "GNU")
+# For now, detect FreeBSD as "Linux"
+elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux" OR ${CMAKE_SYSTEM_NAME} MATCHES "kFreeBSD" OR ${CMAKE_SYSTEM_NAME} MATCHES "GNU" OR ${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
   set_property(TARGET Ableton::Link APPEND PROPERTY
     INTERFACE_COMPILE_DEFINITIONS
     LINK_PLATFORM_LINUX=1
